// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2025, 8:43:52 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Xyris/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/plugins/**/*.{js,ts,mjs}","D:/Xyris/composables/**/*.{js,ts,mjs}","D:/Xyris/utils/**/*.{js,ts,mjs}","D:/Xyris/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Xyris/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;