// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/17/2025, 7:26:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/TEMP/nuxt3-ecomerece-starter/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/plugins/**/*.{js,ts,mjs}","C:/Users/TEMP/nuxt3-ecomerece-starter/composables/**/*.{js,ts,mjs}","C:/Users/TEMP/nuxt3-ecomerece-starter/utils/**/*.{js,ts,mjs}","C:/Users/TEMP/nuxt3-ecomerece-starter/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/TEMP/nuxt3-ecomerece-starter/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;